import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar.jsx";
import { SessionProvider } from "next-auth/react";
import { DM_Sans, Sora } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
	variable: "--font-dm-sans",
	subsets: ["latin"],
});

const sora = Sora({
	variable: "--font-sore",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			className={`${dmSans.variable} ${sora.variable} h-full antialiased`}
		>
			<body className="min-h-full grid grid-cols-1 grid-rows-[auto_1fr] items-start">
				<SessionProvider>
					<Navbar />
				</SessionProvider>
				<div className="container mx-auto max-w-4xl">{children}</div>
				<Footer />
			</body>
		</html>
	);
}
